### ISSUE TITLE
Ping still doesn't go through after ip netns exec vnet ip route add 10.0.1.0 dev veth1 scope link

### ISSUE THREAD

**Issue by rzarai** [ihcsim/netns#1]
The title says it all.  
In the tutorial the ping goes through the interface but not for me.  
How to fix that?  
Also - what should I provide for debugging? What commands you need me to execute?

**Comment by rzarai** [comment]
False alarm. The ping goes through. I decided to ping 10.0.2.0 just to see what happens and it worked for me, and after that I noticed that you also pinged 2.0 the second time, instead of 2.1  
Make a note about it or correct what address you ping in the tutorial.

**Comment by ihcsim** [comment]
Glad to hear it works.

**Comment by rzarai** [comment]
I think it would be a good idea to put a reminder about it in the readme
